version: '1.0'
services:
  web:
    image: van133/mygs:latest
    ports:
      - "80:8080"
    volumes:
      - .:/code
    links:
      - db
  db:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"