version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]

  web:
    image: van133/mygs
    container_name: $APP_NAME
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 80:8080
    environment:
      - SERVER_PORT=8000
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=APP_NAME
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017

    networks:
      - main-network

networks:
  main-network:
    external:
      name: host